### ISSUE TITLE
Remove server sources

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-spark#13]
The server sources are still in the project, and they shouldn't be now that we have things running
from the `jar` files.

**Comment by NicMcPhee** [comment]
Actually, I think this is a "won't do" because I misunderstood what was happening. @devshawn only `jar`ed the _todo_ sources and left the _user_ sources "exposed", which I totally reasonable. If that's correct, then someone (@devshawn) should close this as a "won't do".

**Comment by joethe** [comment]
I agree with Nic.
