### ISSUE TITLE
Improve instructions for Angular portion of lab

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab3_angular-spark#16]
These (in LABTASKS) should be made more specific, and have more documentation about what the expectations are with regard to pipes and stuff.

**Comment by joethe** [comment]
Lenny specifically wants the "??? Profit" part of said instructions to be cleaned up.

**Comment by joethe** [comment]
After grading a couple of the S17 labs here, I'd like to reassert that this is an area in need of improvement. Students didn't seem to always know the difference between Bootstrap and Angular (features), and this sometimes made grading the "use x Angular features" portion a bit annoying.

**Comment by NicMcPhee** [comment]
I think that things have changed enough that this doesn't make sense anymore, so I'm closing it.
