### ISSUE TITLE
An example user test that illustrates mocking services

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-spark#19]
The only test we currently provide is a really weak test of the `home.component`. It would be helpful for the students if we had a test of something in the `User` part of the project that illustrates how to test "real"(er) components, possibly with an example of how to mock out a service.

**Comment by NicMcPhee** [comment]
I've figured out how to mock out the `UserListService` in a simple test of
the `UserListComponent`. Unfortunately I couldn't get it to compile with some
of the nifty filtering stuff in the template, so that's currently commented out,
We obviously want to put that back, however, so it would be awesome
if someone (@joethe? @devshawn?) can figure out how to get that to compile and run.

Also, all that `UserListService` does at the moment is return _all_ the users,
which makes the testing kinda dull. It would be nice to extend `UserListService`
so it also makes the call to the server that returns a `User` with a specific ID.
We could then mock that in a more interesting way, and then either test that
some variant of `UserListComponent` displays a single, correct, user, or have
a new single-user component and test it. I think I can do that if someone can help
me get through the filtering back in.

I found [this part of the Angular 2 docs](https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-dependency)
useful, and cribbed a lot from their [live examples for `welcome.component.spec.ts`](https://embed.plnkr.co/?show=preview).

**Comment by joethe** [comment]
At some point tomorrow I'll do the cleanup for #15, which might at least make dealing with that
a little bit less of a headache. I'll move the filter pipe out to its own module, as per the internet's suggestions, which could make mocking it for testing easier.
