### ISSUE TITLE
Handling the response from the server

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab3_angular-spark#31]
Angular is expecting an observable type for a user array. If we return the user array wrapped in an object, then we can't cast that or auto parse it to the right type. The object we were using had a success field and a data field. rxjs won't parse out the user stuff properly. It was switched in this lab to get the user back and nothing about success. We are not sure if there is a clear way to support the practice of getting to say something about the success and making everything happy.

**Comment by NicMcPhee** [comment]
I'm guessing we'd have to create some sort of new parameterized `ResponseWrapper` class (e.g., `ResponseWrapper<User[]>` on the client side that would peel off the `success` field and provide the desired content.

To be honest, I'm not sure how much we care at the moment. Maybe this would be something to think about more carefully when we have more time?
