### ISSUE TITLE
Consider removing double quotes 

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab3_angular-spark#33]
Apparently, the best practice is considered single quotes... We could consider going through the lab and replacing the double quotes. It's not just a simple find and replace all because there are some strings that have single quotes inside them.

**Comment by NicMcPhee** [comment]
Turns out that IntelliJ has a "Fix TSLint Problems" button that can automate a lot of this, which is nifty. It's especially nice for fixing all the double quote -> single quote conversions, which would have been super tedious otherwise.

**Comment by NicMcPhee** [comment]
I think this is all dealt with now, so I'm closing it.
