### ISSUE TITLE
E2E test may not run on some lab computers

### ISSUE THREAD

**Issue by wallerli** [UMM-CSci-3601/3601-lab3_angular-spark#348]
The version of ChromeDriver being used only supports Chrome version 80, but the chrome version on some lab computers is 79.

**Comment by NicMcPhee** [comment]
Good catch - thanks! 

I wonder if we can just downgrade a library somewhere so it's compatible with Chrome 79?

**Comment by NicMcPhee** [comment]
Also, is there an easy way to identify which computers have this problem? Is it a particular hardware model, or is it more random than that? @floogulinc?

**Comment by kklamberty** [comment]
I manually checked all the lab computers and updated the 4 machines in the teaching lab that were older versions of Chrome. If this happens in lab, now we know how to handle it.
