### ISSUE TITLE
Add user profile page

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab3_angular-spark#349]
I think we should add a user profile page. This would look like `users/[ID]` and be linked to from the full user list. This would allow us to not include all the info in the list and demonstrate more components and routing techniques.

**Comment by kklamberty** [comment]
I like the idea of having a page that includes more information about a user. Maybe something more complicated like a list of all of the previous companies they've worked for in the past or job titles within a company... just some other information that may be more than one element (any collection of things). We had talked about employee as a data type and listing skills or tools they were familiar with. Is it time to switch to something new? Yes, we did users and todos in lab 2, and that would increase the differences between lab 2 and lab 3 for this year at least... but maybe it would be illustrative of a wider variety of interesting things we could do and make it all worth it?
