### ISSUE TITLE
Address TSLint issues

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab3_angular-spark#37]
Our starter code has a lot of "problems" according to TSLint (e.g., we use double quotes when apparently we should be using single quotes). It would be good to get our TSLint issues down to zero (or have reasonable arguments for anything we don't "fix") before we give the code to the students. Then we can expect them to use TSLint and have a small number of issues.

**Comment by NicMcPhee** [comment]
Turns out that IntelliJ has a "Fix TSLint Problems" button that can automate a lot of this, which is nifty. It's especially nice for fixing all the double quote -> single quote conversions, which would have been super tedious otherwise.

**Comment by kklamberty** [comment]
This seems to be working just fine in VS Code. Not sure when that was fixed...
